### ISSUE TITLE
PR: Add support for `eslint-plugin-flowtype-errors`

### ISSUE THREAD

**Issue by amilajack** [johnie/eslint-config-airbnb-flow#1]
This plugin reports flow errors as ESLint errors.

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

https://github.com/amilajack/eslint-plugin-flowtype-errors

Would a PR for this plugin be welcome?

**Comment by johnie** [comment]
@amilajack This look neat! Please submit a PR and I will review 🙂
